# Generated by Django 5.0.6 on 2024-05-30 22:38

from django.db import migrations, models
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('privilegy', '0002_alter_privilege_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='time',
            field=models.DurationField(default=timedelta(days=30)),
            preserve_default=False,
        ),
    ]