# Generated by Django 5.0.6 on 2024-06-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privilegy', '0003_alter_privilege_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='description',
            field=models.TextField(help_text='Use semicolon (;) to separate list items.'),
        ),
    ]
