# Generated by Django 5.0.6 on 2024-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recruiter_username_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
            preserve_default=False,
        ),
    ]
