# Generated by Django 5.0.6 on 2024-05-29 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recruiter_password'),
        ('privilegy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privilege',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='privilegy.privilege'),
        ),
    ]
