# Generated by Django 5.0.6 on 2024-05-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
