# Generated by Django 5.0.6 on 2024-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_status_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internal_currency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
