# Generated by Django 5.0.6 on 2024-06-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_response_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
